osx_image: xcode7.3
language: objective-c
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
env:
  global:
  - FRAMEWORK_NAME=YelpAPI
before_script:
- carthage bootstrap --platform osx, ios
script:
- xctool -project YelpAPI.xcodeproj -scheme YelpAPITests -sdk iphonesimulator9.3 build test
# - pod lib lint =YelpAPI.podspec